### PR TITLE
Adds an event post

### PR DESCRIPTION
**Pull request by SamiSab**
for a good ol'fashioned bathroom party on the Eiffel Tower

### CODE REVIEW

**Comment by fboxwala** [comment]
Nice event :P Can you make the event in the same format as the other files we have already in the content/W2016 folder?

**Comment by ynasser** [comment]
?????

**Comment by fboxwala** [comment]
Hah yomna you've stumbled upon the repository for our git workshop. People
were making silly PRs :)

**Comment by void-elf** [comment]
Yeah! I deleted my comment! I don't know it showed up in my feed :p Github
had a hiccup.

**Pull request closed without merging**
